### ISSUE TITLE
Add test forbidding extending tables in inline arrays

### ISSUE THREAD

**Issue by brandonchinn178** [BurntSushi/toml-test#115]
There should be a test that this is invalid:

```toml
a = [{ b = 1 }]
[a.c]
foo = 1
```

https://github.com/toml-lang/toml/issues/908
