### ISSUE TITLE
Add a test for nested quotes in multi-line strings

### ISSUE THREAD

**Issue by nagisa** [BurntSushi/toml-test#47]
```toml
foo = """
foo "bar" qux
"""
```

should parse foo into a string with `foo "bar" qux` in it. Also variations of this. "Compliant" Python implementations do not understand this construct correctly.

**Comment by Deewiant** [comment]
See also https://github.com/alexcrichton/toml-rs/issues/262: having a quote character at the very end of a string is an edge case.

**Comment by arp242** [comment]
Added/expanded test `valid/multiline-string-quotes` for this:

```toml
lit_one = ''''one quote''''
lit_one_space = ''' 'one quote' '''
lit_two = '''''two quotes'''''
lit_two_space = ''' ''two quotes'' '''
mismatch1 = """aaa'''bbb"""
mismatch2 = '''aaa"""bbb'''
one = """"one quote""""
one_space = """ "one quote" """
two = """""two quotes"""""
two_space = """ ""two quotes"" """
```
