### ISSUE TITLE
Is tests/valid/string-escape-tricky.toml actually valid?

### ISSUE THREAD

**Issue by dmbaturin** [BurntSushi/toml-test#77]
That file has the following lines:

```toml
end_esc = "String does not end here\" but ends here\\"
lit_end_esc = 'String ends here\'

lit_multiline_end = '''There is no escape\'''
```

That would be patently invalid in every programming language that supports breaking long lines with backslashes. For the sake of argument, let's assume that TOML set out to be different and check the spec.

What the spec says is:

>When the last **non-whitespace character on a line** is an unescaped \\, 
>it will be trimmed along with all whitespace (including newlines) up to the next non-whitespace character or closing delimiter.

In those examples, the last non-whitespace character on each line is **not** \\, it's a **quote**! Thus they don't really match the requirement of that passage and shouldn't be valid at all.
